#pragma once

#define SIDE_ID 0
#define RUN_COUNT 1
#define TOTAL_LED_COUNT 20
#define STATIC_IP_ADDR0 10
#define STATIC_IP_ADDR1 10
#define STATIC_IP_ADDR2 0
#define STATIC_IP_ADDR3 2
#define STATIC_NETMASK_ADDR0 255
#define STATIC_NETMASK_ADDR1 0
#define STATIC_NETMASK_ADDR2 0
#define STATIC_NETMASK_ADDR3 0
#define STATIC_GW_ADDR0 10
#define STATIC_GW_ADDR1 10
#define STATIC_GW_ADDR2 0
#define STATIC_GW_ADDR3 1

static const unsigned int LED_COUNT[RUN_COUNT] = {20};
