name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up ESP-IDF
        uses: espressif/setup-esp-idf@v1
        with:
          version: latest
          cache: true

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r tools/requirements.txt

      - name: Run tests
        run: pytest

      - name: Build firmware
        working-directory: firmware
        run: idf.py build
