name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r tools/requirements.txt

      - name: Run Python tests
        run: pytest

      - name: Build host tests
        run: |
          cmake -S firmware/test -B firmware/test/build
          cmake --build firmware/test/build

      - name: Run host tests
        run: ./firmware/test/build/test_rx_task

      - name: Set up ESP-IDF
        uses: espressif/setup-esp-idf@v1
        with:
          version: latest
          cache: true

      - name: Run firmware unit tests
        working-directory: firmware
        run: idf.py test
